repos:
  - repo: https://github.com/rbubley/mirrors-prettier
    rev: v3.8.3
    hooks:
      - id: prettier
        files: .(md|mdx)$
  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.22.1
    hooks:
      - id: markdownlint-cli2
        args:
          - --fix
          - --config
          - .markdownlint-cli2.yaml
        additional_dependencies:
          - markdownlint-sentences-per-line
          - "@jonathan-mayer/markdownlint-rule-titlecase"
        files: \.(md|mdx)$
        types_or: [markdown, mdx]
        types: []
  - repo: local
    hooks:
      - id: eslint
        name: Run ESLint
        entry: npx eslint --fix --config eslint.config.mjs
        language: node
        files: \.(js|jsx|ts|tsx|cts|cjs|mdx)$