import type {LoadContext, Plugin as DocusaurusPlugin} from '@docusaurus/types';
import path from 'path';
import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

export type Config = {
  sidebarConfig: string;
};

// This plugin can generate redirects from a sidebar root path to its first doc.
// It only applies to sidebars configured as a single autogenerated entry.
export function firstDocRedirectPlugin(
  context: LoadContext,
  options: unknown,
): DocusaurusPlugin {
  return {
    name: 'first-doc-redirect',
    contentLoaded: async ({actions}) => {
      const typedOptions = options as Config;
      const imported = await import(
        path.resolve(context.siteDir, typedOptions.sidebarConfig)
      );
      const sidebars = (imported.default ?? imported) as SidebarsConfig;

      Object.keys(sidebars).forEach((sidebar) => {
        const sidebarItems = sidebars[sidebar];
        if (!Array.isArray(sidebarItems) || sidebarItems.length !== 1) {
          return;
        }

        const first = sidebarItems[0];
        if (typeof first === 'string' || first.type !== 'autogenerated') {
          return;
        }

        const autogenerated = first as {type: 'autogenerated'; dirName: string};

        actions.addRoute({
          component: '@site/src/components/FirstDocRedirect.tsx',
          props: {sidebar},
          path: `${context.baseUrl}${autogenerated.dirName}`,
          exact: true,
        });
      });
    },
  };
}


